language: node_js
node_js:
  - "0.11"
  - "0.10"

before_script:
  - "sudo apt-get purge riak"
  - "curl http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.0/ubuntu/precise/riak_2.0.0-1_amd64.deb -O"
  - "sudo dpkg -i riak_2.0.0-1_amd64.deb"
  - "pushd /etc/riak"
  - 'sudo sed -i -e s/"search = off"/"search = on"/ riak.conf'
  - 'sudo sed -i -e s/"storage_backend = bitcask"/"storage_backend = memory"/ riak.conf'
  - "popd"
  - "sudo service riak start"
  - 'until sudo riak-admin test; do sleep 2; done'
